### ISSUE TITLE
Support workflow for manually crafted changelog

### ISSUE THREAD

**Issue by HannesWell** [stefanzweifel/changelog-updater-action#12]
In a project I craft the changelog manually for a release under development below the `[Unreleased]` headline. This gives more precise control over its content and allows me to update the changelog already during development which gives users a 'forecast' about changes for the next release.

As part of the release process I add a headline for the current release directly below the `Unreleased` headline and update the unreleased headlines link.
Similar to [your example in your php-changelog-updater repo](https://github.com/stefanzweifel/php-changelog-updater#expected-changelog-formats) the git-diff looks like the following:

```diff
+## [Unreleased](https://github.com/org/repo/compare/v1.1.0...HEAD)
-## [Unreleased](https://github.com/org/repo/compare/v1.0.0...HEAD)

+## [v1.1.0](https://github.com/org/repo/compare/v1.0.0...v1.1.0) - 2021-02-01

### Added

* New Feature A
* New Feature B
```
Note that the lines describing the new features are already present.

At the moment I'm doing this with a mixture of some bash-commands and the https://github.com/marketplace/actions/find-and-replace action, but I would like to use your action for this task with an empty `release-notes` input.
To only thing that hinders me from doing this is that your action places the headline for the current release immediately above the previous release entry, so my manually added changes remain below the Unreleased headline.
I think it could be worked around, if the upcoming changes would be crafted in a separate file that is read with another action and passed as `release-notes` input. But it would make the workflow more complicated and the 'forecast' would be lost somehow because one would have to look into another file.

It would be great if this action would have an option to place the release-headline immediately below the `Unreleased` headline to obtain the changes outlined above.

**Comment by stefanzweifel** [comment]
Thanks for opening this issue. 
When I created this Action, I wondered when the first user will show up that uses that exact workflow. 😄 

---

I think this could be solved by adding something like a `strategy`-option to the Action and the underlying CLI.
If I understood the concept correctly, the following should happen:

1. Action is run in a Worfklow; no release-notes will be passed.
2. (The Action should not fail due to the missing release notes).
3. The existing "Unreleased" heading should be updated to compare the newest release with `HEAD`
4. A new release heading is created and places directly after the "Unreleased"-heading. (This means that the content between "Unreleased" and the next second level heading is considered as the release-notes for the release)

**Comment by HannesWell** [comment]
> Thanks for opening this issue. When I created this Action, I wondered when the first user will show up that uses that exact workflow. 😄

To be fair, that workflow is not too far from what's already possible. Nevertheless I'm happy to be the first 😄 


> 
> I think this could be solved by adding something like a `strategy`-option to the Action and the underlying CLI. If I understood the concept correctly, the following should happen:
> 
>     1. Action is run in a Worfklow; no release-notes will be passed.
> 
>     2. (The Action should not fail due to the missing release notes).
> 
>     3. The existing "Unreleased" heading should be updated to compare the newest release with `HEAD`
> 
>     4. A new release heading is created and places directly after the "Unreleased"-heading. (This means that the content between "Unreleased" and the next second level heading is considered as the release-notes for the release)

Exactly that's what should happen and a strategy option sounds good. 👍🏽

**Comment by stefanzweifel** [comment]
Quick update on this: I've made `--release-notes` optional in the underlying CLI in https://github.com/stefanzweifel/php-changelog-updater/pull/17.

If no release notes are provided to the CLI we now assume that the content between "Unreleased" and the previous release are the release notes.

You can check the Markdown stubs on how this feature is being tested.
https://github.com/stefanzweifel/php-changelog-updater/pull/17/files#diff-6878944bf9685bab39af8297e322ce70994a07ee66a92051ae95a0727a77647b

No new version of the CLI has been built or tagged yet. Will close this issue once the Action has been updated.

**Comment by stefanzweifel** [comment]
The change has been released in [`v1.4.0`](https://github.com/stefanzweifel/changelog-updater-action/releases/tag/v1.4.0).

**Comment by HannesWell** [comment]
This is great! Thanks a lot already.

I have just tested the new release but unfortunately it did not work as expected and the new headline is still added immediately above the previous release.
Is it possible this is because the `release-notes` input is still required by the action? I did not found any changes in this action to handle it being optional? Maybe it has to be change to be just like to the `release-date` input (I skipped the description):
```
  release-notes:
    required: false
    default: null
```
Furthermore I noticed that an absent `release-date` is checked in PHP by using [`empty()`](https://github.com/stefanzweifel/php-changelog-updater/blob/7b9ea1ce4de0e850bfecdc442108fd75e1ba7de8/app/Commands/UpdateCommand.php#L43) while the absence of `release-notes` is checked vis [`is_null()`](https://github.com/stefanzweifel/php-changelog-updater/blob/c99e1c51863942d37671198c439e01cfc47698ca/app/Actions/PasteReleaseNotesBelowUnreleasedHeading.php#L57).
I'm not familiar with PHP, but could this be a problem too?

**Comment by stefanzweifel** [comment]
Oh, of course that can't work. I knew I forgot something. 🤦 

The `release-notes` has been marked optional in https://github.com/stefanzweifel/changelog-updater-action/pull/16 and the CLI has to be updated as well to use `empty()` in https://github.com/stefanzweifel/changelog-updater-action/pull/16.

>  I'm not familiar with PHP, but could this be a problem too?

That was actually the problem. `is_null()` just checks if the given value is `null`. `empty()` does a similar job but also check if a string is empty `""` or `false` or `0`. [Docs](https://www.php.net/manual/en/function.empty.php#114267).

As the Action always calls the `--release-notes` option but just changes the value, it is safer to use `empty()`.

[v1.4.1](https://github.com/stefanzweifel/changelog-updater-action/releases/tag/v1.4.1) has been released with this fix.

**Comment by HannesWell** [comment]
Great, now it works perfectly fine as expect. 🎉 Thank you!

> > I'm not familiar with PHP, but could this be a problem too?
> 
> That was actually the problem. `is_null()` just checks if the given value is `null`. `empty()` does a similar job but also check if a string is empty `""` or `false` or `0`. [Docs](https://www.php.net/manual/en/function.empty.php#114267).
> 
> As the Action always calls the `--release-notes` option but just changes the value, it is safer to use `empty()`.

Understand. In Java (which I used most) there is also a difference between `null` and an empty `String` which made me wonder.

Just in case you are interested I have applied this change already, to simplify my workflow: https://github.com/axkr/symja_android_library/pull/482
Previously a compare link was not created, so your action not only made the current workflow simpler it also helped me to not make it even more complicated.

**Comment by stefanzweifel** [comment]
👏 👏 👏 

If it's okay for you, I would like to reference your workflow or copy parts of your workflow to the README for this project. So others can see what's possible with the Action.

**Comment by HannesWell** [comment]
> 👏 👏 👏
> 
> If it's okay for you, I would like to reference your workflow or copy parts of your workflow to the README for this project. So others can see what's possible with the Action.

Yes of course, copy or reference whatever you like :)

If you are planning to update the doc, you could also mentioned the new behavior if the `release-notes` input is null/empty in its description in the `actions.yml`.
