### ISSUE TITLE
Add output providing release entry URL

### ISSUE THREAD

**Issue by HannesWell** [stefanzweifel/changelog-updater-action#13]
It would be handy if this action would provide an output variable that contains the URL to the just created release entry in the changelog.

If the `CHANGELOG.md` in an example repo at https://github.com/org/repo contains an release entry like the following
```
## [v1.1.0](https://github.com/org/repo/compare/v1.0.0...v1.1.0) - 2021-02-01

+### Added

* New Feature A
* New Feature B
```

The URL to that entry would be: https://github.com/org/repo/blob/v1.1.0/CHANGELOG.md#v110---2021-02-01

It is basically
`https://github.com/${{ github.repository }}/blob/<default-branch>/<path-to-changelog>#<latest-version>.replace(".","")---<release-date>`
The part after the `#` is just the entry's displayed text with some symbols replaced ("." by "" and " " by "-").
At the moment I'm not sure how one can obtain the default-branch from a GH-context.

For example this URL could be added to a automatically created GH-Release.

**Comment by stefanzweifel** [comment]
> For example this URL could be added to a automatically created GH-Release.

Same question as in #14. Could you elaborate on how you would use this feature in detail? I assume that you would like to update an existing GitHub release with a link to the exact position of the release inside the `CHANGELOg.md`?

---

Also as mentioned in #14.

> The biggest hurdle to implement something like this, is that this Action is very dumb and all the logic lives inside the PHP CLI. Maybe there is an easy way to expose such variables to GitHub Actions from inside the CLI. Have to do some research.

**Comment by HannesWell** [comment]
Same answers as in https://github.com/stefanzweifel/changelog-updater-action/issues/14#issuecomment-1065945569 :)
I would like to create the GH-release in a the workflow from scratch.

**Comment by stefanzweifel** [comment]
As mentioned in https://github.com/stefanzweifel/changelog-updater-action/issues/14#issuecomment-1069562512, the CLI has been prepared to support Actions output.

However, I think this feature request/issue is out of scope for this project. 
To create such an URL, I would need to increase the input given from the user, as the Action/CLI doesn't know anything about the default branch of the repository.
Not the biggest fan of forcing users to pass options to the Action/CLI, that are only being used as a side effect / artifact.

The CLI also isn't really that smart. It doesn't know the repository name. It just takes whats before a `/compare`-string inside the Unreleased heading. 

However, all this information should be available to you inside a GitHub Actions workflow. I'm sure it would be possible to do some string-manipulation in bash to generate this URL.

**Comment by HannesWell** [comment]
> As mentioned in [#14 (comment)](https://github.com/stefanzweifel/changelog-updater-action/issues/14#issuecomment-1069562512), the CLI has been prepared to support Actions output.
> 
> However, I think this feature request/issue is out of scope for this project. To create such an URL, I would need to increase the input given from the user, as the Action/CLI doesn't know anything about the default branch of the repository. Not the biggest fan of forcing users to pass options to the Action/CLI, that are only being used as a side effect / artifact.

This totally makes sense.

Actually it would already sufficient (at least for GH release notes) to have an output like (not sure why I have not suggested it before):
`<path-to-changelog>#<latest-version>.replace(".","")---<release-date>`

or even only the part after the hash/pound-sign. Which one is better probably depends on the exact use case, but with the changelog-file and the pound-sign it seem to be more complete?

So the repo name and the master branch is not necessary and if one really want's to build a full URL it would be as simple as
`https://github.com/${{ github.repository }}/blob/master/${{ steps.update-changelog.outputs.release_entry_repo_link }}`

Assuming the output would be named `release_entry_repo_link`.
If wanted the master element can be replaced by a tag that was also passed as input to this action, so it should be available as well.

> 
> However, all this information should be available to you inside a GitHub Actions workflow. I'm sure it would be possible to do some string-manipulation in bash to generate this URL.

It is definitely possible and I have done this already [here](https://github.com/axkr/symja_android_library/blob/523bf6f6311551c34618a3eb02b35ac66c0e9b0c/.github/workflows/maven-perform-release.yml#L58).
But at least the part to assemble the `release_entry_repo_link` it's not very nice (its a bit cumbersome) and others might want to do that too and IMHO it would be fit quite well to this action and it would lead to a good separation of concerns:
The part `inside` the change-log is handled by this action and everything outside by the outside caller.
For example in case the headline text created by this action changes one day and with that the logic how to assemble the URL -fragment, only the output of this action has to the adjusted correspondingly while users don't have to adjust their workflows.

**Comment by stefanzweifel** [comment]
> Actually it would already sufficient (at least for GH release notes) to have an output like (not sure why I have not suggested it before):
> `<path-to-changelog>#<latest-version>.replace(".","")---<release-date>`

Yeah, this idea went through my head too. 

I think this little bit of string manipulation could really be done in the CLI. Will give this a shot.

**Comment by HannesWell** [comment]
> I think this little bit of string manipulation could really be done in the CLI. Will give this a shot.

That would be nice. Thanks!

**Comment by stefanzweifel** [comment]
This was easier than expected.
As the CLI already contains a Markdown parser/renderer, I used a ["Heading Permalinks"-extension](https://commonmark.thephpleague.com/2.2/extensions/heading-permalinks/) to solve this problem. The extension is responsible for generating the URL fragment for the passed release.

The output is called `RELEASE_URL_FRAGMENT`. Usage ↓

```yaml
- name: Update Changelog
  uses: stefanzweifel/changelog-updater-action@v1
  id: "changelog-updater"
  with:
    # Pass extracted release date, release notes and version to the Action.
    release-date: ${{ steps.release_date.outputs.date }}
    release-notes: ${{ github.event.release.body }}
    latest-version: ${{ github.event.release.tag_name }}
    compare-url-target-revision: ${{ github.event.release.target_commitish }}

- name: "release_url_fragment"
  # #v100---2021-02-01
  run: "https://github.com/org/repo/blob/main/CHANGELOG.md${{ steps.changelog-updater.outputs.release_url_fragment }}"
```

**Comment by HannesWell** [comment]
Very nice! Thank you.
I have tested it and it works great. 🎉
PR https://github.com/axkr/symja_android_library/pull/482 is already updated to use this as well.
