### ISSUE TITLE
Question: Can this be run in an action that generates a release?

### ISSUE THREAD

**Issue by T145** [stefanzweifel/changelog-updater-action#18]
I have an action that generates a release, and then some more logic operates on the repository later. Rather than having this action be triggered when the release is uploaded, is there a way to simply update the changelog alongside the release?

Before this step is where I'd likely insert it: https://github.com/T145/black-mirror/blob/master/.github/workflows/publish_release.yml#L137=

**Comment by stefanzweifel** [comment]
Hi there!

Yes, this is possible. A couple of weeks ago another user had a similar question: #12 
They also have a workflow that doesn't listen to the `release`-trigger.

Here is a link to their workflow:
https://github.com/HannesWell/symja_android_library/blob/286d2d88f9663f1c99a0181e740212839aebeb30/.github/workflows/maven-perform-release.yml#L45-L49

Does this answer your question?

**Comment by T145** [comment]
Yes I just saw that entry in your README and have implemented it: we'll see if my build is successful tomorrow!

**Comment by T145** [comment]
Unfortunately it crashed, requiring release notes. What can be done about this?

https://github.com/T145/black-mirror/runs/6334765249?check_suite_focus=true

**Comment by stefanzweifel** [comment]
What **exactly** are you expecting from your workflow to happen? :)

Scrolling through [publish_release.yml](https://github.com/T145/black-mirror/blob/0455c514efc3f3212cdfc8038ae0180ff4cb39b0/.github/workflows/publish_release.yml) I can't see where you generate/compile release notes that could be added to a CHANGELOG.
There's also nothing in the [scripts](https://github.com/T145/black-mirror/tree/master/scripts)-folder.

The Action – or better the underlying CLI – is clever enough to detect content between an "Unreleased" heading and the next 2nd-level heading and treating it as the release notes for the "new" release, **if** no `release-notes` are passed.

Here are [the tests](https://github.com/stefanzweifel/php-changelog-updater/blob/main/tests/Feature/UpdateCommandTest.php#L211-L232) that cover that feature (written in PHP, but everyone should be able to understand the intent).
Here are the before/after changelogs/markdown files used in the tests:

- Before: https://github.com/stefanzweifel/php-changelog-updater/blob/main/tests/Stubs/base-changelog-with-unreleased-notes.md
- After: https://github.com/stefanzweifel/php-changelog-updater/blob/main/tests/Stubs/expected-changelog-with-unreleased-notes.md

The action expects _some sort of releases notes_ to be added to a CHANGELOG. 
Be it, that the release notes have already manually been added to the CHANGELOG, but tucked under an "Unreleased" heading, or that they are being passed to the action through the `release-notes`-option.

The action tries to follow the [Keep a changelog](https://keepachangelog.com/en/1.0.0/)-format as close as possible. This means that there as to be at least 1 character that acts as release notes.

Or is your plan to just add headings + dates for each release to your CHANGELOG?

**Comment by T145** [comment]
I'm expecting that a GitHub release is generated, and then when committing documents to pull the notes from the release and put them into the changelog. The format those changes are recorded in doesn't matter too much, but just having dates as the headings does sound like a good approach since semantic versioning isn't being used.

So if I'm understanding what you're saying correctly, can I pass in some format to the action and have it insert the release data automatically? How would that be structured?

**Comment by stefanzweifel** [comment]
> […] can I pass in some format to the action and have it insert the release data automatically? How would that be structured?

No, there isn't a "format" option that does all the magic. You either have to:

- provide the release notes in the workflow file itself and pass them through the `release-notes` option (as described in the README)
- have the release notes already prepared in your CHANGELOG **before** the workflow is run. The release notes have to be between a 2nd-level heading called "Unreleased" and another 2nd-level heading.  (like [here](https://raw.githubusercontent.com/stefanzweifel/php-changelog-updater/main/tests/Stubs/base-changelog-with-unreleased-notes.md))

I see that you create a new GitHub release here: https://github.com/T145/black-mirror/blob/0455c514efc3f3212cdfc8038ae0180ff4cb39b0/.github/workflows/publish_release.yml#L66-L73

Where are the release notes for that coming from? Where was the content of [this release](https://github.com/T145/black-mirror/releases/tag/latest) generated? 

As the release is generated inside the workflow run, one can't access `${{ github.event.release.body }}` like when one would follow the simple example in the README. 🤔 


---

The simplest approach is the one listed in the README. Listening on the `release`-trigger and taking the values from the created GitHub release.

I guess you tried this and it didn't trigger the workflow to generate the changelog? This is probably related to [limitations set up by GitHub for the `GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow 
):

> Important: An action can access the GITHUB_TOKEN through the github.token context even if the workflow does not explicitly pass the GITHUB_TOKEN to the action. As a good security practice, you should always make sure that actions only have the minimum access they require by limiting the permissions granted to the GITHUB_TOKEN. For more information, see "[Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)."

I see that you pass `${{ github.token }}` to the `marvinpinto/action-automatic-releases`-Action. According to [the docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret), that the same as `${{ secrets.GITHUB_TOKEN }}`.

Could you maybe give it a shot with [a personal access token](https://github.com/settings/tokens/new)? Create a new PAT, add it as a secret to your repository and pass it as `${{ secrets.PAT }}` to the `action-automatic-releases`-Action.

This should then trigger the `update-changelog.yaml`-workflow as expected.

---

Btw, the value of the `latest-version`-option would also be used as the heading in the CHANGELOG. In the end, your project would then have a changelog like this.

```md
## latest - 2022-05-10

## Commits

- `sha`: ✨🍰✨ (T145)
- `sha`: Commit Message (T145)
- `sha`: Commit Message (T145)

## latest - 2022-05-09

## Commits

- `sha`: ✨🍰✨ (T145)
- `sha`: Commit Message (T145)
- `sha`: Commit Message (T145)

## latest - 2022-05-08

## Commits

- `sha`: ✨🍰✨ (T145)
- `sha`: Commit Message (T145)
- `sha`: Commit Message (T145)

## latest - 2022-05-07

## Commits

- `beb1c4e`: ✨🍰✨ (T145)
- `0455c51`: Attempt changelog update (T145)
```

**Comment by T145** [comment]
> As the release is generated inside the workflow run, one can't access ${{ github.event.release.body }} like when one would follow the simple example in the README. 🤔

Yes, I'm aware of this, and to answer your next section yes, it didn't trigger. Part of my concern is that the release gets published before other documents are committed to the repository. I'm thinking that the spawned action will be at a prior commit, and if either it or the original task finishes first the other will fail due to tracking a different head.

If you can change your `action-automatic-releases` to output the release description then this problem is solved. I'm looking around to see if any other actions can handle this.

> Btw, the value of the latest-version-option would also be used as the heading in the CHANGELOG. In the end, your project would then have a changelog like this.

I assumed that was just designating which tag version the task would target: good to know!

**Comment by T145** [comment]
I'm now having a setup that looks like this:
https://github.com/T145/black-mirror/blob/master/.github/workflows/publish_github_lists.yml#L55=

The action does not crash, but my changelog is not being updated. What am I missing?

**Comment by T145** [comment]
Turns out all the data from `KevinRohn/github-full-release-data` is `null`, which is why nothing gets generated.

**Comment by T145** [comment]
Now I finally a non-null input to this action and the changelog is not being updated. NOW what's wrong?

https://github.com/T145/black-mirror/runs/6397170521?check_suite_focus=true#step:10:9

**Comment by stefanzweifel** [comment]
@T145 The problem could be, that your CHANGELOG is currently empty. 
https://github.com/T145/black-mirror/blob/master/CHANGELOG.md

Could you maybe just add the following to your CHANGELOG?

```md
# Changelog
```

The underlying CLI might have a problem placing the relase notes. (Don't have the code locally to quickly test that and haven't written a test to cover this yet)
The weird thing is, that the Action doesn't fail. 🤔 

Ususally the Action also outputs the updated CHANGELOG to the logs. For example, here are the logs of a recent release of this Action: https://github.com/stefanzweifel/changelog-updater-action/runs/5616773872?check_suite_focus=true#step:4:12

Just for sanity check, could you add the following step after "Update changelog" to show the content of the CHANGELOG?

```yml
      - name: Show CHANGELOG content
        run: cat CHANGELOG.md
```

**Comment by T145** [comment]
Done; I guess we'll see what it generates now!

**Comment by T145** [comment]
Finally fixed!
