### ISSUE TITLE
feat: Add `heading-title` option to change Heading Text independent from `latest-version`

### ISSUE THREAD

**Issue by T145** [stefanzweifel/changelog-updater-action#19]
Presently, the `tag-version` is also set as a heading. But having a way to change this title while also targeting a different tag would be nice. The way I'd approach it is just to add a parameter `heading-title` that defaults to `tag-version`'s value.

**Comment by stefanzweifel** [comment]
Similar to my comment [here](https://github.com/stefanzweifel/changelog-updater-action/issues/20#issuecomment-1126707236): Currently don't have the bandwith to implement this.

"Normal" usage of the Action encourages to use semantic versioning. In that scenario, a new unique tag is created which can act as a heading title.

Will keep that issue open as a possible future addition.

**Comment by stefanzweifel** [comment]
This feature request has been implemented in the just released [`v1.6.0` version](https://github.com/stefanzweifel/changelog-updater-action/releases/tag/v1.6.0) of this Action.

There is a new `heading-title` input option to pass any arbitrary string as the heading text.
I hope this change solves your problem.
