### ISSUE TITLE
feat: Add option to allow adding duplicate releases to CHANGELOG

### ISSUE THREAD

**Issue by T145** [stefanzweifel/changelog-updater-action#20]
I'm getting this message now: https://github.com/T145/black-mirror/runs/6423947857?check_suite_focus=true#step%3A10%3A12=

Which prevents adding new changelog entries unless the tag version is different than the previous heading. Is there a way to disable this?

**Comment by stefanzweifel** [comment]
The feature, to show a warning if a version already exists, was implemented based on feedback from users I received privately. It was implemented in https://github.com/stefanzweifel/php-changelog-updater/pull/16.

> Is there a way to disable this?

There is currently no way to disable this.

I'm currently debating with myself, if it makes sense to add an option to disable the check. A couple of thoughts:

- The Action was built to work with the "Keep a Changelog"-format and expects user to follow it. It was not the idea to be an "all-purpose" changelog-updater Action.
  - Maybe I should change that and make it more universal?
- The goal of the Action is to make it easier to generate **good** changelogs.
  - It seems your project only every generates a single version/release/tag called `latest`. Your CHANGELOG will then contain a list of headings like `latest - YYYY-MM-DD` where the relase notes are (mostly) just an emoji? As there will ony ever be a single tag `latest`, one can't go back to previous releases. What's the purpose of the CHANGELOG then? Showing a list of all the commits made in the last n hours?
- Adding an option to disable this check isn't as easy as it sounds. I've written to "core logic" of the CLI to be independent of a CLI interface. Each new option has to be passed around manually (could be solved by refactoring; which I would like to do one day in the future).

Sorry for the rant. Feeling a bit burnt out at the moment and trying to reduce open-source workload. (I like your idea, but would have to rewrite quite a lot of code for such a niche feature)

**Comment by T145** [comment]
This ties in more to my other feature request than being an independent feature. I also think your implementation is a bit overcomplicated in PHP, as it could probably be better implemented in Python to convert Markdown to HTML and manipulate it using the countless popular libraries to do so. IMO the best thing to do for this situation then would be to just have a `custom-heading` option or something like that to just set the heading to whatever the user wants, w/ the default value being something like `${{ github.ref }} - ${{ current_date }}` which can be declared in `action.yml`.

**Comment by stefanzweifel** [comment]
> I also think your implementation is a bit overcomplicated in PHP, as it could probably be better implemented in Python to convert Markdown to HTML […].

The underlying PHP CLI is probably over engineered and too complicated; I agree. That's something I want to change, when I get the time and the energy to do so.
I have no knowledge with Pyhton, so can't comment on "if Python is better than PHP here".

> IMO the best thing to do for this situation then would be to just have a `custom-heading ` option or something like that to just set the heading to whatever the user wants […]

Agree, that could work if all someone needs are headings like these:

```md
## release name - date
```

In my project I would like to have different headings. Ones that contain a link to GitHub's compare view to make it easier for users to see what exact code has changed in a release. They look like this:

```md
## [v1.3.0](https://github.com/stefanzweifel/changelog-updater-action/compare/v1.2.3...v1.3.0) - 2022-02-09
```

But maybe I can incorporate your idea and allow users to declare their own heading format in `action.yml`. Maybe with something like a "placeholder" system.
