### ISSUE TITLE
Symbols formatted to their html entity code

### ISSUE THREAD

**Issue by Nielsvanpach** [stefanzweifel/changelog-updater-action#3]
First of all, thanks for this action, Stefan!
While using this action, we stumbled upon an issue with the `>` symbol in the release message.

```php
$x->getY()
```
turns into
```php
$x-&gt;getY()
```
and the release after that one makes it
```php
$x-&amp;gt;getY()
```

Examples:
- https://github.com/spatie/enum/commit/cb1f81852c9be7b8ed742f1c0e05066228800991
- https://github.com/spatie/enum/commit/ab186654958b268076987beda3c071997bc8a7d4

**Comment by stefanzweifel** [comment]
Oh no. Thanks for reporting.

I assume this is related to how the internal AST is turned back into markdown. Seems some escaping is happening.

[This is the MarkdownRenderer](https://github.com/stefanzweifel/php-changelog-updater/blob/main/app/MarkdownRenderer.php)-class we use. And this is [the commonmark package](https://github.com/stefanzweifel/commonmark-markdown-renderer) that turns the AST to markdown.

Will take a look later today.

**Comment by stefanzweifel** [comment]
The issue in one of the dependencies has been fixed (https://github.com/stefanzweifel/commonmark-markdown-renderer/pull/2) and a new version of the Action has been released.

As you use `v1` of the Action, nothing has to be updated. Actions will automatically use the latest released version.

**Comment by Nielsvanpach** [comment]
Thanks for the quick fix!
